version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/mernapp
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

volumes:
  mongo-data: